### PR TITLE
Support spring 3.0

### LINKED ISSUE #25: New Version of Spring 3.0
There is a [new version of Spring](https://rubygems.org/gems/spring/versions/3.0.0) available which cannot be installed alongside this gem given this gem's spring version requirements.  It would be nice to see an update to support Spring 3.0.

### PR DESCRIPTION
**Pull request by timdorr**
This loosens the version query for spring to support [the newly released 3.0](https://github.com/rails/spring/blob/master/CHANGELOG.md#300). [The changes](https://github.com/rails/spring/compare/v2.1.1...v3.0.0) appear to be mostly around dropping support for older Rails versions, so there shouldn't be any changes needed in this library.

Closes #25

### CODE REVIEW

**Comment by timdorr** [comment]
BTW, if folks want to use this now, just use my repo temporarily:
```ruby
gem 'spring-watcher-listen', github: 'timdorr/spring-watcher-listen'
```
You *should* have it in a `:development` group, so it won't affect your production workloads, in case you're worried about me doing evil things 😃

**Review by mario-amazing — APPROVED** [review]

**Comment by humphreyja** [comment]
@timdorr Thanks for doing this! Rails 7 alpha2 won't run without this change due to a change that breaks Spring. It is fixed in 3.0. Looking forward to having this merged in.

**Comment by FraDim** [comment]
Hey @jonleighton  👋

In case this missed you, do you have any plans on releasing this?

**Comment by jonleighton** [comment]
@FraDim thanks for the ping, I hadn't seen this.

I'm no longer really involved in maintaining Spring (I'm actually 100% using Elixir these days...)

Given that this gem is a dependency of Rails, and Spring itself is already managed by the Rails org, I think it would make sense to transfer this repo and the gem management to the Rails org. WDYT @fxn @rafaelfranca?

**Comment by rafaelfranca** [comment]
Sounds good to me.

**Comment by h0jeZvgoxFepBQ2C** [comment]
@rafaelfranca Could you merge this PR? Thank you!

**Comment by rafaelfranca** [comment]
I can't merge anything yet. Jon needs to transfer first.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thanks so much @jonleighton ! ❤️

**Comment by jonleighton** [comment]
@rafaelfranca OK, I have done the following:

* Initiate transfer of the repo to your personal GitHub. I couldn't tranfser to Rails because I got the error "You don't have permission to create public repos in this org". I think it's because I'm in the Rails org but don't have full permissions. You could accept the transfer and then transfer onwards to the Rails org.
* Added you to the gem owners
* Merged this PR and fixed up tests

I intended to release a new version with this change, but there is still one failing test (due to https://github.com/rails/spring/commit/87dc8cee8f0fb463c256775d58ae5ad627fe7410):

```
  1) Error:
ListenWatcherTest#test_add_directory_with_dangling_symlink:
NoMethodError: undefined method `check_stale' for #<Spring::Watcher::Listen:0x000055e32be04fe8 @_mutex=#<Thread::Mutex:0x000055e32be04db8>, @root="/tmp/d20211104-1368267-iy8664", @latency=0.001, @files=#<Set: {}>, @directories=#<Set: {"/tmp/d20211104-1368267-iy8664/subdir"}>, @stale=false, @listeners=[], @on_debug=nil>
    /home/turnip/.gem/ruby/3.0.0/bundler/gems/spring-7ca995584bed/test/support/watcher_test.rb:189:in `block in <class:WatcherTest>'
```

So I thought I'd let you decide what's the best solution for that.

Thanks :pray:

**Comment by afdev82** [comment]
> I can't merge anything yet. Jon needs to transfer first.

@rafaelfranca jonleighton did that, but we need a new version (#27). The repo is still under jonleighton, I don't see any repo in your account / Rails org. Thanks!

**Comment by rafaelfranca** [comment]
Oh, that is right. It seems the transfer expired before I could accept. @jonleighton can you start it again please?

**Comment by jonleighton** [comment]
@rafaelfranca I have re-initiated the transfer. I also added you to as a repo collaborator because I thought then I could make you an owner and you can do it in your own time, but I can't actually see a way to achieve that (maybe because I'm not paying for GitHub...)

**Comment by toobulkeh** [comment]
Bump for @rafaelfranca after the holidays :)

**Comment by afdev82** [comment]
> Bump for @rafaelfranca after the holidays :)

This PR is merged, it's missing only a new version.
See [this open issue](https://github.com/rails/spring-watcher-listen/issues/27) for the support for Spring v4.

**Comment by toobulkeh** [comment]
It's merged—but not released as a gem. Since the transfer it needs a new release!

**Comment by feliperaul** [comment]
While a new release doesn't happen, you can fix it by pointing your gemfile to use the master branch, since the patch was already merged:

```
gem 'spring-watcher-listen', github: "rails/spring-watcher-listen", branch: "master"
```

Also, if you're updating (to rails 7 for instance), use `bundle update spring spring-watcher-listen` afterwards (be sure to unlock your spring version in your gemfile if it's locked, you need at least version 3)

**Comment by konalegi** [comment]
Do you have any plans to release it anytime soon?
Thanks!

**Comment by Mange** [comment]
Please don't let "perfect" become the enemy of the "good". Just because the gem cannot support Spring 4 doesn't mean some people would like to update older codebases to Spring 3 first.
Upgrading everything right up until the edge of requiring newer versions of Ruby, then upgrading Ruby, and then moving along, for example.

I don't think there should be anything blocking this from being released in a new version and when Spring 4 support is added later, then that is just another new release.
